INSERT INTO countries (name, url, airports, code) VALUES ('Afghanistan', 'https://www.flightradar24.com/data/airports/afghanistan', 11, 'AFG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Albania', 'https://www.flightradar24.com/data/airports/albania', 2, 'ALB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Algeria', 'https://www.flightradar24.com/data/airports/algeria', 33, 'DZA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('American Samoa', 'https://www.flightradar24.com/data/airports/american-samoa', 1, 'ASM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Angola', 'https://www.flightradar24.com/data/airports/angola', 14, 'AGO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Anguilla', 'https://www.flightradar24.com/data/airports/anguilla', 1, 'AIA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Antarctica', 'https://www.flightradar24.com/data/airports/antarctica', 14, 'ATA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Antigua And Barbuda', 'https://www.flightradar24.com/data/airports/antigua-and-barbuda', 2, 'ATG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Argentina', 'https://www.flightradar24.com/data/airports/argentina', 48, 'ARG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Armenia', 'https://www.flightradar24.com/data/airports/armenia', 3, 'ARM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Aruba', 'https://www.flightradar24.com/data/airports/aruba', 1, 'ABW') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Australia', 'https://www.flightradar24.com/data/airports/australia', 397, 'AUS') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Austria', 'https://www.flightradar24.com/data/airports/austria', 13, 'AUT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Azerbaijan', 'https://www.flightradar24.com/data/airports/azerbaijan', 7, 'AZE') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bahamas', 'https://www.flightradar24.com/data/airports/bahamas', 31, 'BHS') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bahrain', 'https://www.flightradar24.com/data/airports/bahrain', 2, 'BHR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bangladesh', 'https://www.flightradar24.com/data/airports/bangladesh', 8, 'BGD') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Barbados', 'https://www.flightradar24.com/data/airports/barbados', 1, 'BRB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Belarus', 'https://www.flightradar24.com/data/airports/belarus', 6, 'BLR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Belgium', 'https://www.flightradar24.com/data/airports/belgium', 6, 'BEL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Belize', 'https://www.flightradar24.com/data/airports/belize', 10, 'BLZ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Benin', 'https://www.flightradar24.com/data/airports/benin', 1, 'BEN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bermuda', 'https://www.flightradar24.com/data/airports/bermuda', 1, 'BMU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bhutan', 'https://www.flightradar24.com/data/airports/bhutan', 4, 'BTN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bolivia', 'https://www.flightradar24.com/data/airports/bolivia', 17, 'BOL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bosnia And Herzegovina', 'https://www.flightradar24.com/data/airports/bosnia-and-herzegovina', 4, 'BIH') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Botswana', 'https://www.flightradar24.com/data/airports/botswana', 4, 'BWA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Brazil', 'https://www.flightradar24.com/data/airports/brazil', 210, 'BRA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Brunei', 'https://www.flightradar24.com/data/airports/brunei', 1, 'BRN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Bulgaria', 'https://www.flightradar24.com/data/airports/bulgaria', 6, 'BGR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Burkina Faso', 'https://www.flightradar24.com/data/airports/burkina-faso', 1, 'BFA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Burundi', 'https://www.flightradar24.com/data/airports/burundi', 1, 'BDI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cambodia', 'https://www.flightradar24.com/data/airports/cambodia', 4, 'KHM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cameroon', 'https://www.flightradar24.com/data/airports/cameroon', 9, 'CMR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Canada', 'https://www.flightradar24.com/data/airports/canada', 295, 'CAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cape Verde', 'https://www.flightradar24.com/data/airports/cape-verde', 7, 'CPV') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cayman Islands', 'https://www.flightradar24.com/data/airports/cayman-islands', 3, 'CYM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Central African Republic', 'https://www.flightradar24.com/data/airports/central-african-republic', 2, 'CAF') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Chad', 'https://www.flightradar24.com/data/airports/chad', 1, 'TCD') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Chile', 'https://www.flightradar24.com/data/airports/chile', 20, 'CHL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('China', 'https://www.flightradar24.com/data/airports/china', 252, 'CHN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cocos (keeling) Islands', 'https://www.flightradar24.com/data/airports/cocos-keeling-islands', 1, 'CCK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Colombia', 'https://www.flightradar24.com/data/airports/colombia', 58, 'COL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Comoros', 'https://www.flightradar24.com/data/airports/comoros', 2, 'COM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Congo', 'https://www.flightradar24.com/data/airports/congo', 2, 'COG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cook Islands', 'https://www.flightradar24.com/data/airports/cook-islands', 2, 'COK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Costa Rica', 'https://www.flightradar24.com/data/airports/costa-rica', 16, 'CRI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Croatia', 'https://www.flightradar24.com/data/airports/croatia', 9, 'HRV') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cuba', 'https://www.flightradar24.com/data/airports/cuba', 13, 'CUB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Curacao', 'https://www.flightradar24.com/data/airports/curacao', 1, 'CUW') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Cyprus', 'https://www.flightradar24.com/data/airports/cyprus', 3, 'CYP') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Czechia', 'https://www.flightradar24.com/data/airports/czechia', 17, 'CZE') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Democratic Republic Of The Congo', 'https://www.flightradar24.com/data/airports/democratic-republic-of-the-congo', 16, 'COD') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Denmark', 'https://www.flightradar24.com/data/airports/denmark', 20, 'DNK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Djibouti', 'https://www.flightradar24.com/data/airports/djibouti', 1, 'DJI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Dominica', 'https://www.flightradar24.com/data/airports/dominica', 2, 'DMA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Dominican Republic', 'https://www.flightradar24.com/data/airports/dominican-republic', 8, 'DOM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Ecuador', 'https://www.flightradar24.com/data/airports/ecuador', 13, 'ECU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Egypt', 'https://www.flightradar24.com/data/airports/egypt', 17, 'EGY') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('El Salvador', 'https://www.flightradar24.com/data/airports/el-salvador', 2, 'SLV') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Equatorial Guinea', 'https://www.flightradar24.com/data/airports/equatorial-guinea', 4, 'GNQ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Eritrea', 'https://www.flightradar24.com/data/airports/eritrea', 1, 'ERI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Estonia', 'https://www.flightradar24.com/data/airports/estonia', 5, 'EST') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Eswatini', 'https://www.flightradar24.com/data/airports/eswatini', 2, 'SWZ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Ethiopia', 'https://www.flightradar24.com/data/airports/ethiopia', 21, 'ETH') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Falkland Islands (malvinas)', 'https://www.flightradar24.com/data/airports/falkland-islands-malvinas', 2, 'FLK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Faroe Islands', 'https://www.flightradar24.com/data/airports/faroe-islands', 1, 'FRO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Fiji', 'https://www.flightradar24.com/data/airports/fiji', 11, 'FJI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Finland', 'https://www.flightradar24.com/data/airports/finland', 23, 'FIN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('France', 'https://www.flightradar24.com/data/airports/france', 133, 'FRA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('French Guiana', 'https://www.flightradar24.com/data/airports/french-guiana', 1, 'GUF') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('French Polynesia', 'https://www.flightradar24.com/data/airports/french-polynesia', 45, 'PYF') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Gabon', 'https://www.flightradar24.com/data/airports/gabon', 3, 'GAB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Gambia', 'https://www.flightradar24.com/data/airports/gambia', 1, 'GMB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Georgia', 'https://www.flightradar24.com/data/airports/georgia', 3, 'GEO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Germany', 'https://www.flightradar24.com/data/airports/germany', 121, 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Ghana', 'https://www.flightradar24.com/data/airports/ghana', 6, 'GHA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Gibraltar', 'https://www.flightradar24.com/data/airports/gibraltar', 1, 'GIB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Greece', 'https://www.flightradar24.com/data/airports/greece', 39, 'GRC') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Greenland', 'https://www.flightradar24.com/data/airports/greenland', 15, 'GRL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Grenada', 'https://www.flightradar24.com/data/airports/grenada', 1, 'GRD') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Guadeloupe', 'https://www.flightradar24.com/data/airports/guadeloupe', 4, 'GLP') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Guam', 'https://www.flightradar24.com/data/airports/guam', 2, 'GUM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Guatemala', 'https://www.flightradar24.com/data/airports/guatemala', 5, 'GTM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Guernsey', 'https://www.flightradar24.com/data/airports/guernsey', 2, 'GGY') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Guinea', 'https://www.flightradar24.com/data/airports/guinea', 1, 'GIN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Guinea-bissau', 'https://www.flightradar24.com/data/airports/guinea-bissau', 1, 'GNB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Guyana', 'https://www.flightradar24.com/data/airports/guyana', 3, 'GUY') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Haiti', 'https://www.flightradar24.com/data/airports/haiti', 3, 'HTI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Honduras', 'https://www.flightradar24.com/data/airports/honduras', 6, 'HND') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Hong Kong', 'https://www.flightradar24.com/data/airports/hong-kong', 1, 'HKG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Hungary', 'https://www.flightradar24.com/data/airports/hungary', 11, 'HUN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Iceland', 'https://www.flightradar24.com/data/airports/iceland', 16, 'ISL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('India', 'https://www.flightradar24.com/data/airports/india', 128, 'IND') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Indonesia', 'https://www.flightradar24.com/data/airports/indonesia', 134, 'IDN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Iran', 'https://www.flightradar24.com/data/airports/iran', 64, 'IRN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Iraq', 'https://www.flightradar24.com/data/airports/iraq', 7, 'IRQ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Ireland', 'https://www.flightradar24.com/data/airports/ireland', 9, 'IRL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Isle Of Man', 'https://www.flightradar24.com/data/airports/isle-of-man', 1, 'IMN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Israel', 'https://www.flightradar24.com/data/airports/israel', 3, 'ISR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Italy', 'https://www.flightradar24.com/data/airports/italy', 71, 'ITA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Ivory Coast', 'https://www.flightradar24.com/data/airports/ivory-coast', 4, 'CIV') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Jamaica', 'https://www.flightradar24.com/data/airports/jamaica', 3, 'JAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Japan', 'https://www.flightradar24.com/data/airports/japan', 84, 'JPN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Jersey', 'https://www.flightradar24.com/data/airports/jersey', 1, 'JEY') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Jordan', 'https://www.flightradar24.com/data/airports/jordan', 3, 'JOR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Kazakhstan', 'https://www.flightradar24.com/data/airports/kazakhstan', 23, 'KAZ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Kenya', 'https://www.flightradar24.com/data/airports/kenya', 27, 'KEN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Kiribati', 'https://www.flightradar24.com/data/airports/kiribati', 11, 'KIR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Kosovo', 'https://www.flightradar24.com/data/airports/kosovo', 1, 'XKX') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Kuwait', 'https://www.flightradar24.com/data/airports/kuwait', 1, 'KWT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Kyrgyzstan', 'https://www.flightradar24.com/data/airports/kyrgyzstan', 3, 'KGZ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Laos', 'https://www.flightradar24.com/data/airports/laos', 8, 'LAO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Latvia', 'https://www.flightradar24.com/data/airports/latvia', 3, 'LVA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Lebanon', 'https://www.flightradar24.com/data/airports/lebanon', 1, 'LBN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Lesotho', 'https://www.flightradar24.com/data/airports/lesotho', 1, 'LSO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Liberia', 'https://www.flightradar24.com/data/airports/liberia', 1, 'LBR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Libya', 'https://www.flightradar24.com/data/airports/libya', 10, 'LBY') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Lithuania', 'https://www.flightradar24.com/data/airports/lithuania', 4, 'LTU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Luxembourg', 'https://www.flightradar24.com/data/airports/luxembourg', 1, 'LUX') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Macao', 'https://www.flightradar24.com/data/airports/macao', 1, 'MAC') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Madagascar', 'https://www.flightradar24.com/data/airports/madagascar', 12, 'MDG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Malawi', 'https://www.flightradar24.com/data/airports/malawi', 2, 'MWI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Malaysia', 'https://www.flightradar24.com/data/airports/malaysia', 35, 'MYS') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Maldives', 'https://www.flightradar24.com/data/airports/maldives', 18, 'MDV') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Mali', 'https://www.flightradar24.com/data/airports/mali', 2, 'MLI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Malta', 'https://www.flightradar24.com/data/airports/malta', 1, 'MLT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Marshall Islands', 'https://www.flightradar24.com/data/airports/marshall-islands', 2, 'MHL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Martinique', 'https://www.flightradar24.com/data/airports/martinique', 1, 'MTQ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Mauritania', 'https://www.flightradar24.com/data/airports/mauritania', 3, 'MRT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Mauritius', 'https://www.flightradar24.com/data/airports/mauritius', 2, 'MUS') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Mayotte', 'https://www.flightradar24.com/data/airports/mayotte', 1, 'MYT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Mexico', 'https://www.flightradar24.com/data/airports/mexico', 75, 'MEX') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Micronesia', 'https://www.flightradar24.com/data/airports/micronesia', 4, 'FSM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Moldova', 'https://www.flightradar24.com/data/airports/moldova', 1, 'MDA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Monaco', 'https://www.flightradar24.com/data/airports/monaco', 1, 'MCO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Mongolia', 'https://www.flightradar24.com/data/airports/mongolia', 9, 'MNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Montenegro', 'https://www.flightradar24.com/data/airports/montenegro', 2, 'MNE') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Montserrat', 'https://www.flightradar24.com/data/airports/montserrat', 1, 'MSR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Morocco', 'https://www.flightradar24.com/data/airports/morocco', 21, 'MAR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Mozambique', 'https://www.flightradar24.com/data/airports/mozambique', 12, 'MOZ') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Myanmar (burma)', 'https://www.flightradar24.com/data/airports/myanmar-burma', 28, 'MMR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Namibia', 'https://www.flightradar24.com/data/airports/namibia', 11, 'NAM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Nauru', 'https://www.flightradar24.com/data/airports/nauru', 1, 'NRU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Nepal', 'https://www.flightradar24.com/data/airports/nepal', 20, 'NPL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Netherlands', 'https://www.flightradar24.com/data/airports/netherlands', 16, 'NLD') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('New Caledonia', 'https://www.flightradar24.com/data/airports/new-caledonia', 10, 'NCL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('New Zealand', 'https://www.flightradar24.com/data/airports/new-zealand', 44, 'NZL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Nicaragua', 'https://www.flightradar24.com/data/airports/nicaragua', 4, 'NIC') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Niger', 'https://www.flightradar24.com/data/airports/niger', 4, 'NER') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Nigeria', 'https://www.flightradar24.com/data/airports/nigeria', 22, 'NGA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('North Korea', 'https://www.flightradar24.com/data/airports/north-korea', 1, 'PRK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('North Macedonia', 'https://www.flightradar24.com/data/airports/north-macedonia', 2, 'MKD') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Northern Mariana Islands', 'https://www.flightradar24.com/data/airports/northern-mariana-islands', 3, 'MNP') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Norway', 'https://www.flightradar24.com/data/airports/norway', 55, 'NOR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Oman', 'https://www.flightradar24.com/data/airports/oman', 6, 'OMN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Pakistan', 'https://www.flightradar24.com/data/airports/pakistan', 21, 'PAK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Palau', 'https://www.flightradar24.com/data/airports/palau', 1, 'PLW') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Panama', 'https://www.flightradar24.com/data/airports/panama', 10, 'PAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Papua New Guinea', 'https://www.flightradar24.com/data/airports/papua-new-guinea', 31, 'PNG') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Paraguay', 'https://www.flightradar24.com/data/airports/paraguay', 2, 'PRY') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Peru', 'https://www.flightradar24.com/data/airports/peru', 28, 'PER') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Philippines', 'https://www.flightradar24.com/data/airports/philippines', 48, 'PHL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Poland', 'https://www.flightradar24.com/data/airports/poland', 31, 'POL') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Portugal', 'https://www.flightradar24.com/data/airports/portugal', 26, 'PRT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Puerto Rico', 'https://www.flightradar24.com/data/airports/puerto-rico', 9, 'PRI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Qatar', 'https://www.flightradar24.com/data/airports/qatar', 3, 'QAT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Reunion', 'https://www.flightradar24.com/data/airports/reunion', 2, 'REU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Romania', 'https://www.flightradar24.com/data/airports/romania', 18, 'ROU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Russia', 'https://www.flightradar24.com/data/airports/russia', 167, 'RUS') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Rwanda', 'https://www.flightradar24.com/data/airports/rwanda', 2, 'RWA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Saint Helena', 'https://www.flightradar24.com/data/airports/saint-helena', 2, 'SHN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Saint Kitts And Nevis', 'https://www.flightradar24.com/data/airports/saint-kitts-and-nevis', 2, 'KNA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Saint Lucia', 'https://www.flightradar24.com/data/airports/saint-lucia', 2, 'LCA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Saint Pierre And Miquelon', 'https://www.flightradar24.com/data/airports/saint-pierre-and-miquelon', 1, 'SPM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Saint Vincent And The Grenadines', 'https://www.flightradar24.com/data/airports/saint-vincent-and-the-grenadines', 5, 'VCT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Samoa', 'https://www.flightradar24.com/data/airports/samoa', 1, 'WSM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Sao Tome And Principe', 'https://www.flightradar24.com/data/airports/sao-tome-and-principe', 2, 'STP') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Saudi Arabia', 'https://www.flightradar24.com/data/airports/saudi-arabia', 28, 'SAU') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Senegal', 'https://www.flightradar24.com/data/airports/senegal', 4, 'SEN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Serbia', 'https://www.flightradar24.com/data/airports/serbia', 3, 'SRB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Seychelles', 'https://www.flightradar24.com/data/airports/seychelles', 2, 'SYC') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Sierra Leone', 'https://www.flightradar24.com/data/airports/sierra-leone', 2, 'SLE') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Singapore', 'https://www.flightradar24.com/data/airports/singapore', 2, 'SGP') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Slovakia', 'https://www.flightradar24.com/data/airports/slovakia', 6, 'SVK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Slovenia', 'https://www.flightradar24.com/data/airports/slovenia', 3, 'SVN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Solomon Islands', 'https://www.flightradar24.com/data/airports/solomon-islands', 14, 'SLB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Somalia', 'https://www.flightradar24.com/data/airports/somalia', 7, 'SOM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('South Africa', 'https://www.flightradar24.com/data/airports/south-africa', 29, 'ZAF') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('South Korea', 'https://www.flightradar24.com/data/airports/south-korea', 15, 'KOR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('South Sudan', 'https://www.flightradar24.com/data/airports/south-sudan', 4, 'SSD') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Spain', 'https://www.flightradar24.com/data/airports/spain', 57, 'ESP') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Sri Lanka', 'https://www.flightradar24.com/data/airports/sri-lanka', 7, 'LKA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Sudan', 'https://www.flightradar24.com/data/airports/sudan', 7, 'SDN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Suriname', 'https://www.flightradar24.com/data/airports/suriname', 2, 'SUR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Sweden', 'https://www.flightradar24.com/data/airports/sweden', 50, 'SWE') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Switzerland', 'https://www.flightradar24.com/data/airports/switzerland', 19, 'CHE') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Syria', 'https://www.flightradar24.com/data/airports/syria', 4, 'SYR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Taiwan', 'https://www.flightradar24.com/data/airports/taiwan', 16, 'TWN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Tajikistan', 'https://www.flightradar24.com/data/airports/tajikistan', 4, 'TJK') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Tanzania', 'https://www.flightradar24.com/data/airports/tanzania', 22, 'TZA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Thailand', 'https://www.flightradar24.com/data/airports/thailand', 35, 'THA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Timor-leste (east Timor)', 'https://www.flightradar24.com/data/airports/timor-leste-east-timor', 5, 'TLS') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Togo', 'https://www.flightradar24.com/data/airports/togo', 1, 'TGO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Tonga', 'https://www.flightradar24.com/data/airports/tonga', 3, 'TON') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Trinidad And Tobago', 'https://www.flightradar24.com/data/airports/trinidad-and-tobago', 2, 'TTO') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Tunisia', 'https://www.flightradar24.com/data/airports/tunisia', 8, 'TUN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Turkey', 'https://www.flightradar24.com/data/airports/turkey', 57, 'TUR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Turkmenistan', 'https://www.flightradar24.com/data/airports/turkmenistan', 6, 'TKM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Turks And Caicos Islands', 'https://www.flightradar24.com/data/airports/turks-and-caicos-islands', 3, 'TCA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Tuvalu', 'https://www.flightradar24.com/data/airports/tuvalu', 1, 'TUV') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Uganda', 'https://www.flightradar24.com/data/airports/uganda', 8, 'UGA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Ukraine', 'https://www.flightradar24.com/data/airports/ukraine', 20, 'UKR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('United Arab Emirates', 'https://www.flightradar24.com/data/airports/united-arab-emirates', 12, 'ARE') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('United Kingdom', 'https://www.flightradar24.com/data/airports/united-kingdom', 116, 'GBR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('United States', 'https://www.flightradar24.com/data/airports/united-states', 1395, 'USA') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('United States Minor Outlying Islands', 'https://www.flightradar24.com/data/airports/united-states-minor-outlying-islands', 1, 'UMI') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Uruguay', 'https://www.flightradar24.com/data/airports/uruguay', 3, 'URY') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Uzbekistan', 'https://www.flightradar24.com/data/airports/uzbekistan', 12, 'UZB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Vanuatu', 'https://www.flightradar24.com/data/airports/vanuatu', 5, 'VUT') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Venezuela', 'https://www.flightradar24.com/data/airports/venezuela', 21, 'VEN') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Vietnam', 'https://www.flightradar24.com/data/airports/vietnam', 22, 'VNM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Virgin Islands British', 'https://www.flightradar24.com/data/airports/virgin-islands-british', 3, 'VGB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Virgin Islands Us', 'https://www.flightradar24.com/data/airports/virgin-islands-us', 2, 'VIR') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Wallis And Futuna', 'https://www.flightradar24.com/data/airports/wallis-and-futuna', 2, 'WLF') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Yemen', 'https://www.flightradar24.com/data/airports/yemen', 5, 'YEM') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Zambia', 'https://www.flightradar24.com/data/airports/zambia', 5, 'ZMB') ON CONFLICT (code) DO NOTHING;
INSERT INTO countries (name, url, airports, code) VALUES ('Zimbabwe', 'https://www.flightradar24.com/data/airports/zimbabwe', 3, 'ZWE') ON CONFLICT (code) DO NOTHING;
